name: carbonized
description: A fluent date and time library for Dart - inspired by PHP Carbon. Intuitive API for date manipulation, localization (170+ locales), timezones, comparisons, and human-readable differences.
version: 0.1.0
homepage: https://routeddart.github.io/carbonized/
repository: https://github.com/RoutedDart/carbonized
resolution: workspace
environment:
  sdk: ">=3.9.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  clock: ^1.1.2
  intl: ^0.20.2
  meta: ^1.17.0
  time_machine2: ^0.13.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
